import express from 'express';
import nodemailer from 'nodemailer';

const router = express.Router();

router.post('/send-email', async (req, res) => {
  const { email, hooks, insights } = req.body;

  if (!email || !hooks) {
    return res.status(400).json({ error: "Email and hooks are required." });
  }

  try {
    const transporter = nodemailer.createTransport({
      service: 'gmail',
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS
      }
    });

    // Build HTML email content
    let htmlContent = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; color: #333;">
        <h2 style="color: #2563eb;">Your AI Generated Hooks</h2>
        <p>Here are your freshly generated hooks based on the latest trends:</p>
    `;

    hooks.forEach((hook, i) => {
      htmlContent += `
        <div style="margin-bottom: 20px; padding: 15px; background: #f3f4f6; border-left: 4px solid #3b82f6; border-radius: 4px;">
          <p style="font-size: 16px; font-weight: bold; margin: 0 0 10px 0;">${hook}</p>
        </div>
      `;
    });

    if (insights && insights.length > 0) {
      htmlContent += `
        <h3 style="margin-top: 30px; color: #4b5563;">Latest Trends & Insights</h3>
        <ul>
      `;
      insights.forEach(insight => {
        htmlContent += `<li style="margin-bottom: 10px;">${insight}</li>`;
      });
      htmlContent += `</ul>`;
    }

    htmlContent += `
        <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #e5e7eb; font-size: 12px; color: #6b7280;">
          <p>Generated by GrowthHooks AI Engine</p>
        </div>
      </div>
    `;

    const mailOptions = {
      from: process.env.EMAIL_USER,
      to: email,
      subject: '🔥 Your GrowthHooks are ready!',
      html: htmlContent
    };

    await transporter.sendMail(mailOptions);
    res.json({ message: "Email sent successfully" });

  } catch (error) {
    console.error("Email error:", error);
    res.status(500).json({ error: "Failed to send email. Check configuration." });
  }
});

export default router;
